server {
  listen 80;
  server_name _;

  # Carpeta donde Nginx servirá tu build de Vite
  root /usr/share/nginx/html;
  index index.html;

  # Manejo de rutas de React/Vite SPA (Single Page Application)
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Cache estático de assets
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf)$ {
    expires 30d;
    add_header Cache-Control "public, no-transform";
  }

  # Redirección de errores comunes
  error_page 404 /index.html;
  error_page 500 502 503 504 /index.html;
}
